/** Block registry: ids, properties, drops, tool tiers. */

export const B = {
  AIR: 0,
  GRASS: 1,
  DIRT: 2,
  STONE: 3,
  COBBLE: 4,
  SAND: 5,
  GRAVEL: 6,
  SNOW: 7,
  ICE: 8,
  WATER: 9,
  LOG_OAK: 10,
  LOG_BIRCH: 11,
  LEAVES_OAK: 12,
  LEAVES_BIRCH: 13,
  PLANKS: 14,
  CRAFTING_TABLE: 15,
  FURNACE: 16,
  TORCH: 17,
  GLASS: 18,
  BRICKS: 19,
  COAL_ORE: 20,
  IRON_ORE: 21,
  GOLD_ORE: 22,
  DIAMOND_ORE: 23,
  BEDROCK: 24,
  SNOW_BLOCK: 25,
  CACTUS: 26,
  // items (not placeable as world blocks in simple path, but usable as item ids)
  STICK: 50,
  COAL: 51,
  IRON_INGOT: 52,
  GOLD_INGOT: 53,
  DIAMOND: 54,
  WOOD_PICK: 60,
  STONE_PICK: 61,
  IRON_PICK: 62,
  WOOD_SWORD: 63,
};

export const BlockDefs = {
  [B.GRASS]: {
    name: "草方块",
    solid: true,
    opaque: true,
    hardness: 0.6,
    tool: "shovel",
    minTier: 0,
    drop: B.DIRT,
    tex: { top: "grass_top", side: "grass_side", bottom: "dirt" },
  },
  [B.DIRT]: {
    name: "泥土",
    solid: true,
    opaque: true,
    hardness: 0.5,
    tool: "shovel",
    minTier: 0,
    drop: B.DIRT,
    tex: { all: "dirt" },
  },
  [B.STONE]: {
    name: "石头",
    solid: true,
    opaque: true,
    hardness: 1.5,
    tool: "pickaxe",
    minTier: 1,
    drop: B.COBBLE,
    tex: { all: "stone" },
  },
  [B.COBBLE]: {
    name: "圆石",
    solid: true,
    opaque: true,
    hardness: 2,
    tool: "pickaxe",
    minTier: 1,
    drop: B.COBBLE,
    tex: { all: "cobble" },
  },
  [B.SAND]: {
    name: "沙子",
    solid: true,
    opaque: true,
    hardness: 0.5,
    tool: "shovel",
    minTier: 0,
    drop: B.SAND,
    tex: { all: "sand" },
  },
  [B.GRAVEL]: {
    name: "沙砾",
    solid: true,
    opaque: true,
    hardness: 0.6,
    tool: "shovel",
    minTier: 0,
    drop: B.GRAVEL,
    tex: { all: "gravel" },
  },
  [B.SNOW]: {
    name: "雪",
    solid: true,
    opaque: true,
    hardness: 0.3,
    tool: "shovel",
    minTier: 0,
    drop: B.SNOW_BLOCK,
    tex: { all: "snow" },
  },
  [B.ICE]: {
    name: "冰",
    solid: true,
    opaque: false,
    hardness: 0.5,
    tool: "pickaxe",
    minTier: 0,
    drop: B.AIR,
    tex: { all: "ice" },
  },
  [B.WATER]: {
    name: "水",
    solid: false,
    opaque: false,
    liquid: true,
    hardness: 100,
    drop: B.AIR,
    tex: { all: "water" },
  },
  [B.LOG_OAK]: {
    name: "橡木原木",
    solid: true,
    opaque: true,
    hardness: 2,
    tool: "axe",
    minTier: 0,
    drop: B.LOG_OAK,
    tex: { top: "log_top", side: "log_oak", bottom: "log_top" },
  },
  [B.LOG_BIRCH]: {
    name: "白桦原木",
    solid: true,
    opaque: true,
    hardness: 2,
    tool: "axe",
    minTier: 0,
    drop: B.LOG_BIRCH,
    tex: { top: "log_top_birch", side: "log_birch", bottom: "log_top_birch" },
  },
  [B.LEAVES_OAK]: {
    name: "橡树树叶",
    solid: true,
    opaque: false,
    hardness: 0.2,
    drop: B.AIR,
    tex: { all: "leaves_oak" },
  },
  [B.LEAVES_BIRCH]: {
    name: "白桦树叶",
    solid: true,
    opaque: false,
    hardness: 0.2,
    drop: B.AIR,
    tex: { all: "leaves_birch" },
  },
  [B.PLANKS]: {
    name: "木板",
    solid: true,
    opaque: true,
    hardness: 2,
    tool: "axe",
    minTier: 0,
    drop: B.PLANKS,
    tex: { all: "planks" },
  },
  [B.CRAFTING_TABLE]: {
    name: "工作台",
    solid: true,
    opaque: true,
    hardness: 2.5,
    tool: "axe",
    minTier: 0,
    drop: B.CRAFTING_TABLE,
    tex: { top: "craft_top", side: "craft_side", bottom: "planks" },
  },
  [B.FURNACE]: {
    name: "熔炉",
    solid: true,
    opaque: true,
    hardness: 3.5,
    tool: "pickaxe",
    minTier: 1,
    drop: B.FURNACE,
    tex: { top: "furnace_top", side: "furnace_side", front: "furnace_front", bottom: "furnace_top" },
  },
  [B.TORCH]: {
    name: "火把",
    solid: false,
    opaque: false,
    hardness: 0.1,
    drop: B.TORCH,
    tex: { all: "torch" },
  },
  [B.GLASS]: {
    name: "玻璃",
    solid: true,
    opaque: false,
    hardness: 0.3,
    drop: B.AIR,
    tex: { all: "glass" },
  },
  [B.BRICKS]: {
    name: "砖块",
    solid: true,
    opaque: true,
    hardness: 2,
    tool: "pickaxe",
    minTier: 1,
    drop: B.BRICKS,
    tex: { all: "bricks" },
  },
  [B.COAL_ORE]: {
    name: "煤矿石",
    solid: true,
    opaque: true,
    hardness: 3,
    tool: "pickaxe",
    minTier: 1,
    drop: B.COAL,
    tex: { all: "coal_ore" },
  },
  [B.IRON_ORE]: {
    name: "铁矿石",
    solid: true,
    opaque: true,
    hardness: 3,
    tool: "pickaxe",
    minTier: 2,
    drop: B.IRON_ORE,
    tex: { all: "iron_ore" },
  },
  [B.GOLD_ORE]: {
    name: "金矿石",
    solid: true,
    opaque: true,
    hardness: 3,
    tool: "pickaxe",
    minTier: 2,
    drop: B.GOLD_ORE,
    tex: { all: "gold_ore" },
  },
  [B.DIAMOND_ORE]: {
    name: "钻石矿石",
    solid: true,
    opaque: true,
    hardness: 3,
    tool: "pickaxe",
    minTier: 3,
    drop: B.DIAMOND,
    tex: { all: "diamond_ore" },
  },
  [B.BEDROCK]: {
    name: "基岩",
    solid: true,
    opaque: true,
    hardness: 1000,
    unbreakable: true,
    drop: B.AIR,
    tex: { all: "bedrock" },
  },
  [B.SNOW_BLOCK]: {
    name: "雪块",
    solid: true,
    opaque: true,
    hardness: 0.2,
    drop: B.SNOW_BLOCK,
    tex: { all: "snow" },
  },
  [B.CACTUS]: {
    name: "仙人掌",
    solid: true,
    opaque: true,
    hardness: 0.4,
    drop: B.CACTUS,
    tex: { all: "cactus" },
  },
  // Items
  [B.STICK]: { name: "木棍", item: true, drop: B.STICK, tex: { all: "stick" } },
  [B.COAL]: { name: "煤炭", item: true, drop: B.COAL, tex: { all: "coal" } },
  [B.IRON_INGOT]: { name: "铁锭", item: true, drop: B.IRON_INGOT, tex: { all: "iron_ingot" } },
  [B.GOLD_INGOT]: { name: "金锭", item: true, drop: B.GOLD_INGOT, tex: { all: "gold_ingot" } },
  [B.DIAMOND]: { name: "钻石", item: true, drop: B.DIAMOND, tex: { all: "diamond" } },
  [B.WOOD_PICK]: {
    name: "木镐",
    item: true,
    tool: "pickaxe",
    tier: 1,
    speed: 2,
    drop: B.WOOD_PICK,
    tex: { all: "wood_pick" },
  },
  [B.STONE_PICK]: {
    name: "石镐",
    item: true,
    tool: "pickaxe",
    tier: 2,
    speed: 4,
    drop: B.STONE_PICK,
    tex: { all: "stone_pick" },
  },
  [B.IRON_PICK]: {
    name: "铁镐",
    item: true,
    tool: "pickaxe",
    tier: 3,
    speed: 6,
    drop: B.IRON_PICK,
    tex: { all: "iron_pick" },
  },
  [B.WOOD_SWORD]: {
    name: "木剑",
    item: true,
    tool: "sword",
    tier: 1,
    speed: 1.5,
    drop: B.WOOD_SWORD,
    tex: { all: "wood_sword" },
  },
};

export function isPlaceable(id) {
  const d = BlockDefs[id];
  return !!d && !d.item && id !== B.AIR;
}

export function isSolid(id) {
  const d = BlockDefs[id];
  return !!(d && d.solid);
}

export function isOpaque(id) {
  const d = BlockDefs[id];
  return !!(d && d.opaque);
}

export function isLiquid(id) {
  const d = BlockDefs[id];
  return !!(d && d.liquid);
}

export function blockName(id) {
  return BlockDefs[id]?.name ?? "空";
}

/** Placeable blocks shown in creative inventory. */
export const CREATIVE_BLOCKS = [
  B.GRASS, B.DIRT, B.STONE, B.COBBLE, B.SAND, B.GRAVEL, B.SNOW, B.ICE,
  B.LOG_OAK, B.LOG_BIRCH, B.LEAVES_OAK, B.LEAVES_BIRCH, B.PLANKS,
  B.CRAFTING_TABLE, B.FURNACE, B.TORCH, B.GLASS, B.BRICKS,
  B.COAL_ORE, B.IRON_ORE, B.GOLD_ORE, B.DIAMOND_ORE, B.SNOW_BLOCK, B.CACTUS,
  B.WATER,
];

export const ALL_ITEMS = [
  ...CREATIVE_BLOCKS,
  B.STICK, B.COAL, B.IRON_INGOT, B.GOLD_INGOT, B.DIAMOND,
  B.WOOD_PICK, B.STONE_PICK, B.IRON_PICK, B.WOOD_SWORD,
];
